- id: '1779573953376'
  alias: Lamps on Sunset
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    target:
      device_id:
      - b91791e9672f2f44a25595059f2e5761
      - 872530f1d7a4d513b24b9ebecdf68fdc
    data:
      color_temp_kelvin: 2829
  mode: single
