name: cloudflared

services:

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./cloudflared:/etc/cloudflared
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks: [web]

networks:
  web:
    external: true
